dist: trusty

language: generic

env:
    - OPTIONS='-php'
    - OPTIONS='-js'
    - OPTIONS='-python'

before_script:
    - phpenv global 5.6
    - nvm install 5

script: sudo bash test.sh ${OPTIONS}
